[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
[functions]
  node_bundler = "esbuild"
 # external_node_modules = ["@netlify/blobs"]
  included_files = ["netlify/functions/**/*.cjs", "netlify/functions/_admin_users.json"]
